### PR TITLE
Bug fixes

### LINKED ISSUE #35: Make a separate command for parsing
Make a separate command for parsing in case control panel doesn't work.

### LINKED ISSUE #57: Give /yoink command
Title.

### PR DESCRIPTION
**Pull request by ewang2002**
This pull request:
- Adds a `logkey` command.
- Adds a `yoink` command (Resolves #57)
- Adds a `parse` command (Resolves #35)
- Adds the add/remove/change name command.
- Adds more quota options, particularly for securities (Responding to Modmail, adding/removing/changing names)
- Actually counts responding to modmail, adding/removing/changing names towards quota when applicable
- Changes the README and project name.
- Renames the OneLifeBot.ts file (and associated class) to just Bot.ts (and Bot). **This is why there are many changes.**

I didn't test this as much as I'd like to, although I'm fairly confident that this should work just fine. Please double check for me (if possible) and let me know if something doesn't work as expected. Thanks!

### CODE REVIEW

File: src/commands/staff/AddOrChangeName.ts [hunk 1]
```diff
@@ -0,0 +1,363 @@
+import {ArgumentType, BaseCommand, ICommandContext, ICommandInfo} from "../BaseCommand";
```
Comment (dmansdman) [inline src/commands/staff/AddOrChangeName.ts:1]: AddOrChangeName

1. Crashes when I attempt to edit one of my nicknames in the database.  Crash occurs once a name is selected in the dropdown.  It could be a result of my perms (bot developer role), since it works on the test user provided.  Details of crash below.
image
image

2. Consider rewording "Edit" to "Replace" since that is what ends up happening when we edit a name.
"Do you want to add NAME or replace one of dmansdmans names with NAME"
Add, Replace, Cancel
image

Comment (dmansdman) [reply src/commands/staff/AddOrChangeName.ts:1]: Are you sure you want to replace one of  @!TestT  | nameThree | nameFour's names with NEWNAME? Select an IGN to replace with the new IGN.  Otherwise, press the Cancel button
image

Comment (dmansdman) [reply src/commands/staff/AddOrChangeName.ts:1]: BUG: Name was not replaced: 
image

File: src/commands/staff/RemoveName.ts [hunk 2]
```diff
@@ -0,0 +1,222 @@
+import {ArgumentType, BaseCommand, ICommandContext, ICommandInfo} from "../BaseCommand";
```
Comment (dmansdman) [inline src/commands/staff/RemoveName.ts:1]: Crash when I attempt to remove one of my names.  Again, similar to issue with AddorChangeNames. 
image
image

Comment (dmansdman) [reply src/commands/staff/RemoveName.ts:1]: Works as intended for example account.

File: src/commands/staff/AddOrChangeName.ts (hunk 1 above)
Comment (dmansdman) [reply src/commands/staff/AddOrChangeName.ts:1]: Weird behavior where I could change Beep's nickname once, but could not change it again.  If intended, needs clarification for user.
image

File: src/commands/staff/RemoveName.ts (hunk 2 above)
Comment (dmansdman) [reply src/commands/staff/RemoveName.ts:1]: Again, weird issue with Beep.
image

File: src/commands/staff/AddOrChangeName.ts (hunk 1 above)
Comment (dmansdman) [reply src/commands/staff/AddOrChangeName.ts:1]: I removed all nicknames.  Then I added "GoodBeep" but it was "already in database."  Then I removed "GoodBeep" and it wasn't there.  I think these commands have lots of weird interactions to resolve.

image

File: src/commands/logging/LogKeyPop.ts [hunk 3]
```diff
@@ -0,0 +1,163 @@
+import {ArgumentType, BaseCommand, ICommandContext, ICommandInfo} from "../BaseCommand";
```
Comment (dmansdman) [inline src/commands/logging/LogKeyPop.ts:1]: Works as intended.  Might consider allowing changing the number of keys/person within the command, rather than forcing a rerun of the command.

File: src/commands/modmail/ReplyToThread.ts [hunk 4]
```diff
@@ -1,6 +1,7 @@
 import {ArgumentType, BaseCommand, ICommandContext} from "../BaseCommand";
```
Comment (dmansdman) [inline src/commands/modmail/ReplyToThread.ts:1]: Works as intended.

File: src/commands/staff/ParseRaidVc.ts [hunk 5]
```diff
@@ -0,0 +1,110 @@
+import {BaseCommand, ICommandContext, ICommandInfo} from "../BaseCommand";
```
Comment (dmansdman) [inline src/commands/staff/ParseRaidVc.ts:1]: Works but could be a little prettier
image

File: src/instances/RaidInstance.ts [hunk 6]
```diff
@@ -1333,19 +1333,70 @@ export class RaidInstance {
         return raidObj;
     }
 
+    /**
```
Comment (dmansdman) [inline src/instances/RaidInstance.ts:1336]: Remind me to ask what this is for.

File: src/managers/UserManager.ts [hunk 7]
```diff
@@ -5,7 +5,7 @@ import {MongoManager} from "./MongoManager";
 import {IIdNameInfo, IUserInfo} from "../definitions";
```
Comment (dmansdman) [inline src/managers/UserManager.ts:5]: This caused problems when I tried to replace my nicknames.  Consider handling things like "null" for rawName, or consider why null is being passed into this function in the first place.  When I checked for null and returned "", getAllNames crashed because of null.  Just review these methods and how they are being called.

**Review by dmansdman — CHANGES_REQUESTED** [review]
Will discuss with you, but there are some issues with the name commands and other small improvements.  Overall solid work though!

**Review by dmansdman — APPROVED** [review]
Approved
